{'name': 'Real Estate',
 'version': 'Version',
 'summary': 'A real estates addon',
 'description': 'An addon for managing real estates. Supports adding properties with their types and tags. Also recording offers made to buy those properties ',
 'category': 'Sales',
 'author': 'Uxio Mendez Pazos',
 'website': 'Website',
 'depends': ['base'],
 'application': True,
 'data':
     ['security/ir.model.access.csv',
      'views/estate_property_views.xml',
      'views/estate_property_type_views.xml',
      'views/estate_property_tag_views.xml',
      'views/estate_property_offer_views.xml',
      'views/estate_menus.xml',
      'views/res_users_views.xml',
      ],
 }
